spring:
  application:
    name: test-example

  show-sql: true
  properties.hibernate.format_sql: true
  properties.hibernate.temp.use_jdbc_metadata_defaults: false
  spring.main.allow-bean-definition-overriding: true


# Database
spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/pokedex
  username: postgres
  password: postgres
  initialization-mode: always

server:
  port: 8080

